HYPOTHESES = [
    {
        "hypothesis": "baseline",
        "rationale": "Reference XGBoost configuration.",
        "params": {
            "n_estimators": 200,
            "max_depth": 6,
            "learning_rate": 0.1,
            "subsample": 0.8,
            "colsample_bytree": 0.8,
            "objective": "binary:logistic",
            "eval_metric": "logloss",
            "tree_method": "hist",
            "random_state": 42,
        },
    },
    {
        "hypothesis": "shallower_trees",
        "rationale": "Shallower trees may reduce overfitting and noisy boundaries.",
        "params": {
            "n_estimators": 200,
            "max_depth": 4,
            "learning_rate": 0.1,
            "subsample": 0.8,
            "colsample_bytree": 0.8,
            "objective": "binary:logistic",
            "eval_metric": "logloss",
            "tree_method": "hist",
            "random_state": 42,
        },
    },
    {
        "hypothesis": "lower_lr_more_trees",
        "rationale": "Lower learning rate with more trees may improve generalisation.",
        "params": {
            "n_estimators": 400,
            "max_depth": 6,
            "learning_rate": 0.05,
            "subsample": 0.8,
            "colsample_bytree": 0.8,
            "objective": "binary:logistic",
            "eval_metric": "logloss",
            "tree_method": "hist",
            "random_state": 42,
        },
    },
    {
        "hypothesis": "more_row_sampling",
        "rationale": "Lower subsample may improve robustness by adding stochasticity.",
        "params": {
            "n_estimators": 200,
            "max_depth": 6,
            "learning_rate": 0.1,
            "subsample": 0.6,
            "colsample_bytree": 0.8,
            "objective": "binary:logistic",
            "eval_metric": "logloss",
            "tree_method": "hist",
            "random_state": 42,
        },
    },
    {
        "hypothesis": "more_feature_sampling",
        "rationale": "Lower colsample_bytree may reduce over-reliance on a few dominant colour features.",
        "params": {
            "n_estimators": 200,
            "max_depth": 6,
            "learning_rate": 0.1,
            "subsample": 0.8,
            "colsample_bytree": 0.6,
            "objective": "binary:logistic",
            "eval_metric": "logloss",
            "tree_method": "hist",
            "random_state": 42,
        },
    },
]